#!/usr/bin/env python
"""
Copyright 2011 Wordnik, Inc.
 
    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0
 
    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

class DocDocInputFilesInput:
    """

    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """

    def __init__(self):
        self.swaggerTypes = {
            'userId': 'str',
            'fileId': 'str',
            'pageNumber': 'str',
            'pageCount': 'str',
            'quality': 'str',
            'usePdf': 'str'
        }



        # User GUID
        self.userId = None # str


        # File GUID
        self.fileId = None # str


        # Page Number
        self.pageNumber = None # str


        # Page Count
        self.pageCount = None # str


        # Quality
        self.quality = None # str


        # Use Pdf
        self.usePdf = None # str

