#!/usr/bin/env python
"""
Copyright 2011 Wordnik, Inc.
 
    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0
 
    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

class StorageStorageInputFoldersInput:
    """

    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """

    def __init__(self):
        self.swaggerTypes = {
            'userId': 'str',
            'path': 'str',
            'pageIndex': 'str',
            'pageSize': 'str',
            'orderBy': 'str',
            'orderAsc': 'str',
            'filter': 'str',
            'fileTypes': 'str',
            'extended': 'str'
        }



        # User GUID
        self.userId = None # str


        # Path
        self.path = None # str


        # Page Index
        self.pageIndex = None # str


        # Page Size
        self.pageSize = None # str


        # Order By
        self.orderBy = None # str


        # Order Asc
        self.orderAsc = None # str


        # Filter
        self.filter = None # str


        # File Types
        self.fileTypes = None # str


        # Indicates whether an extended information should be returned
        self.extended = None # str

