#!/usr/bin/env python
"""
Copyright 2011 Wordnik, Inc.
 
    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0
 
    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

class TestData:
    """

    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """

    def __init__(self):
        self.swaggerTypes = {
            'documentDetailsResponseList': 'List<DocumentDetailsResponse>',
            'changesResponseList': 'List<ChangesResponse>',
            'changesResultList': 'List<ChangesResult>',
            'documentDetailsResultList': 'List<DocumentDetailsResult>',
            'compareResultList': 'List<CompareResult>',
            'pageList': 'List<Page>',
            'compareResponseList': 'List<CompareResponse>',
            'rectangleList': 'List<Rectangle>',
            'changeInfoList': 'List<ChangeInfo>',
            'resetPasswordResultList': 'List<ResetPasswordResult>',
            'createUserResultList': 'List<CreateUserResult>',
            'userPasswordInfoList': 'List<UserPasswordInfo>',
            'updateStorageProviderResponseList': 'List<UpdateStorageProviderResponse>',
            'createUserResponseList': 'List<CreateUserResponse>',
            'changePasswordResultList': 'List<ChangePasswordResult>',
            'updateUserResponseList': 'List<UpdateUserResponse>',
            'addStorageProviderResponseList': 'List<AddStorageProviderResponse>',
            'updateUserResultList': 'List<UpdateUserResult>',
            'userInfoResponseList': 'List<UserInfoResponse>',
            'getStorageProvidersResultList': 'List<GetStorageProvidersResult>',
            'resetPasswordResponseList': 'List<ResetPasswordResponse>',
            'updateStorageProviderResultList': 'List<UpdateStorageProviderResult>',
            'userInfoList': 'List<UserInfo>',
            'addStorageProviderResultList': 'List<AddStorageProviderResult>',
            'getStorageProvidersResponseList': 'List<GetStorageProvidersResponse>',
            'userInfoResultList': 'List<UserInfoResult>',
            'storageProviderInfoList': 'List<StorageProviderInfo>',
            'changePasswordResponseList': 'List<ChangePasswordResponse>',
            'setCollaboratorsResponseList': 'List<SetCollaboratorsResponse>',
            'listRepliesResultList': 'List<ListRepliesResult>',
            'listAnnotationsResponseList': 'List<ListAnnotationsResponse>',
            'rangeList': 'List<Range>',
            'annotationInfoList': 'List<AnnotationInfo>',
            'getCollaboratorsResponseList': 'List<GetCollaboratorsResponse>',
            'userIdentityList': 'List<UserIdentity>',
            'moveAnnotationResultList': 'List<MoveAnnotationResult>',
            'editReplyResponseList': 'List<EditReplyResponse>',
            'addReplyResultList': 'List<AddReplyResult>',
            'addReplyResponseList': 'List<AddReplyResponse>',
            'createAnnotationResponseList': 'List<CreateAnnotationResponse>',
            'deleteAnnotationResultList': 'List<DeleteAnnotationResult>',
            'deleteAnnotationResponseList': 'List<DeleteAnnotationResponse>',
            'createAnnotationResultList': 'List<CreateAnnotationResult>',
            'annotationReplyInfoList': 'List<AnnotationReplyInfo>',
            'listRepliesResponseList': 'List<ListRepliesResponse>',
            'moveAnnotationResponseList': 'List<MoveAnnotationResponse>',
            'editReplyResultList': 'List<EditReplyResult>',
            'listAnnotationsResultList': 'List<ListAnnotationsResult>',
            'setCollaboratorsResultList': 'List<SetCollaboratorsResult>',
            'pointList': 'List<Point>',
            'getCollaboratorsResultList': 'List<GetCollaboratorsResult>',
            'resultList': 'List<Result>',
            'getJobsDocumentsResultList': 'List<GetJobsDocumentsResult>',
            'getJobDocumentsResultList': 'List<GetJobDocumentsResult>',
            'createJobResponseList': 'List<CreateJobResponse>',
            'getJobDocumentsResponseList': 'List<GetJobDocumentsResponse>',
            'createJobResultList': 'List<CreateJobResult>',
            'getJobsResponseList': 'List<GetJobsResponse>',
            'jobInputDocumentList': 'List<JobInputDocument>',
            'convertResponseList': 'List<ConvertResponse>',
            'getJobResponseList': 'List<GetJobResponse>',
            'addJobDocumentResponseList': 'List<AddJobDocumentResponse>',
            'getJobsDocumentsResponseList': 'List<GetJobsDocumentsResponse>',
            'getJobsResultList': 'List<GetJobsResult>',
            'updateJobResponseList': 'List<UpdateJobResponse>',
            'getJobResultList': 'List<GetJobResult>',
            'jobOutputDocumentList': 'List<JobOutputDocument>',
            'convertRequestResultList': 'List<ConvertRequestResult>',
            'jobDocumentsEntryList': 'List<JobDocumentsEntry>',
            'jobInfoList': 'List<JobInfo>',
            'addJobDocumentResultList': 'List<AddJobDocumentResult>',
            'viewDocumentResultList': 'List<ViewDocumentResult>',
            'viewDocumentResponseList': 'List<ViewDocumentResponse>',
            'dimensionList': 'List<Dimension>',
            'createPackageResultList': 'List<CreatePackageResult>',
            'uploadResponseList': 'List<UploadResponse>',
            'compressResponseList': 'List<CompressResponse>',
            'deleteResultList': 'List<DeleteResult>',
            'createFolderResultList': 'List<CreateFolderResult>',
            'folderMoveResultList': 'List<FolderMoveResult>',
            'fileMoveResultList': 'List<FileMoveResult>',
            'listEntitiesResultList': 'List<ListEntitiesResult>',
            'fileSystemDocumentList': 'List<FileSystemDocument>',
            'createFolderResponseList': 'List<CreateFolderResponse>',
            'documentInfoList': 'List<DocumentInfo>',
            'compressRequestResultList': 'List<CompressRequestResult>',
            'uploadRequestResultList': 'List<UploadRequestResult>',
            'storageInfoResultList': 'List<StorageInfoResult>',
            'createPackageResponseList': 'List<CreatePackageResponse>',
            'folderMoveResponseList': 'List<FolderMoveResponse>',
            'storageInfoResponseList': 'List<StorageInfoResponse>',
            'fileSystemFolderList': 'List<FileSystemFolder>',
            'deleteResponseList': 'List<DeleteResponse>',
            'listEntitiesResponseList': 'List<ListEntitiesResponse>',
            'fileMoveResponseList': 'List<FileMoveResponse>',
            'getDocumentInfoResultList': 'List<GetDocumentInfoResult>',
            'templateFieldList': 'List<TemplateField>',
            'documentViewsResultList': 'List<DocumentViewsResult>',
            'sharedDocumentsResponseList': 'List<SharedDocumentsResponse>',
            'templateFieldsResponseList': 'List<TemplateFieldsResponse>',
            'documentAccessInfoResultList': 'List<DocumentAccessInfoResult>',
            'sharedUsersResultList': 'List<SharedUsersResult>',
            'sharedDocumentsResultList': 'List<SharedDocumentsResult>',
            'documentViewsResponseList': 'List<DocumentViewsResponse>',
            'getDocumentForeignTypesResponseList': 'List<GetDocumentForeignTypesResponse>',
            'documentViewInfoList': 'List<DocumentViewInfo>',
            'sharedUsersResponseList': 'List<SharedUsersResponse>',
            'getDocumentInfoResponseList': 'List<GetDocumentInfoResponse>',
            'documentUserStatusResultList': 'List<DocumentUserStatusResult>',
            'documentUserStatusResponseList': 'List<DocumentUserStatusResponse>',
            'templateFieldsResultList': 'List<TemplateFieldsResult>',
            'getDocumentForeignTypesResultList': 'List<GetDocumentForeignTypesResult>',
            'documentAccessInfoResponseList': 'List<DocumentAccessInfoResponse>',
            'sharedDocumentInfoList': 'List<SharedDocumentInfo>',
            'questionnaireExecutionInfoList': 'List<QuestionnaireExecutionInfo>',
            'getQuestionnairesResponseList': 'List<GetQuestionnairesResponse>',
            'getDocumentQuestionnairesResultList': 'List<GetDocumentQuestionnairesResult>',
            'addDocumentDataSourceResponseList': 'List<AddDocumentDataSourceResponse>',
            'getDatasourceResultList': 'List<GetDatasourceResult>',
            'getDatasourcesResponseList': 'List<GetDatasourcesResponse>',
            'addDocumentQuestionnaireResponseList': 'List<AddDocumentQuestionnaireResponse>',
            'updateQuestionnaireResultList': 'List<UpdateQuestionnaireResult>',
            'addQuestionnaireExecutionResponseList': 'List<AddQuestionnaireExecutionResponse>',
            'deleteDatasourceResponseList': 'List<DeleteDatasourceResponse>',
            'createQuestionnaireResultList': 'List<CreateQuestionnaireResult>',
            'createQuestionnaireResponseList': 'List<CreateQuestionnaireResponse>',
            'questionnaireInfoList': 'List<QuestionnaireInfo>',
            'addDatasourceResultList': 'List<AddDatasourceResult>',
            'questionnairePageInfoList': 'List<QuestionnairePageInfo>',
            'updateQuestionnaireExecutionResponseList': 'List<UpdateQuestionnaireExecutionResponse>',
            'getQuestionnaireExecutionsResultList': 'List<GetQuestionnaireExecutionsResult>',
            'deleteQuestionnaireResultList': 'List<DeleteQuestionnaireResult>',
            'getDocumentQuestionnairesResponseList': 'List<GetDocumentQuestionnairesResponse>',
            'getDatasourceResponseList': 'List<GetDatasourceResponse>',
            'addQuestionnaireExecutionResultList': 'List<AddQuestionnaireExecutionResult>',
            'deleteDocumentQuestionnaireResponseList': 'List<DeleteDocumentQuestionnaireResponse>',
            'mergeTemplateResponseList': 'List<MergeTemplateResponse>',
            'deleteDocumentQuestionnaireResultList': 'List<DeleteDocumentQuestionnaireResult>',
            'getQuestionnairesResultList': 'List<GetQuestionnairesResult>',
            'getQuestionnaireExecutionsResponseList': 'List<GetQuestionnaireExecutionsResponse>',
            'deleteQuestionnaireResponseList': 'List<DeleteQuestionnaireResponse>',
            'questionInfoList': 'List<QuestionInfo>',
            'datasourceList': 'List<Datasource>',
            'getQuestionnaireResultList': 'List<GetQuestionnaireResult>',
            'mergeTemplateResultList': 'List<MergeTemplateResult>',
            'answerInfoList': 'List<AnswerInfo>',
            'getDatasourcesResultList': 'List<GetDatasourcesResult>',
            'updateQuestionnaireExecutionResultList': 'List<UpdateQuestionnaireExecutionResult>',
            'addDocumentDataSourceResultList': 'List<AddDocumentDataSourceResult>',
            'deleteDatasourceResultList': 'List<DeleteDatasourceResult>',
            'addDocumentQuestionnaireResultList': 'List<AddDocumentQuestionnaireResult>',
            'updateQuestionnaireResponseList': 'List<UpdateQuestionnaireResponse>',
            'addDatasourceResponseList': 'List<AddDatasourceResponse>',
            'getQuestionnaireResponseList': 'List<GetQuestionnaireResponse>',
            'datasourceFieldList': 'List<DatasourceField>',
            'renameResponseList': 'List<RenameResponse>',
            'renameResultList': 'List<RenameResult>',
            'signatureEnvelopeDocumentsResponseList': 'List<SignatureEnvelopeDocumentsResponse>',
            'signatureFieldInfoList': 'List<SignatureFieldInfo>',
            'signatureContactResponseList': 'List<SignatureContactResponse>',
            'signatureEnvelopesResultList': 'List<SignatureEnvelopesResult>',
            'signatureTemplateFieldLocationInfoList': 'List<SignatureTemplateFieldLocationInfo>',
            'signatureTemplateDocumentResultList': 'List<SignatureTemplateDocumentResult>',
            'signatureContactsResponseList': 'List<SignatureContactsResponse>',
            'signatureFieldResultList': 'List<SignatureFieldResult>',
            'signatureSignatureInfoList': 'List<SignatureSignatureInfo>',
            'signatureTemplateFieldsResponseList': 'List<SignatureTemplateFieldsResponse>',
            'signatureEnvelopeInfoList': 'List<SignatureEnvelopeInfo>',
            'signatureTemplateFieldSettingsList': 'List<SignatureTemplateFieldSettings>',
            'signatureTemplateFieldLocationSettingsList': 'List<SignatureTemplateFieldLocationSettings>',
            'signatureEnvelopeRecipientResultList': 'List<SignatureEnvelopeRecipientResult>',
            'signatureTemplateFieldResponseList': 'List<SignatureTemplateFieldResponse>',
            'signatureEnvelopesResponseList': 'List<SignatureEnvelopesResponse>',
            'signatureEnvelopeFieldInfoList': 'List<SignatureEnvelopeFieldInfo>',
            'signatureRoleInfoList': 'List<SignatureRoleInfo>',
            'signatureTemplateSettingsList': 'List<SignatureTemplateSettings>',
            'signatureTemplateFieldsResultList': 'List<SignatureTemplateFieldsResult>',
            'signatureContactsImportResultList': 'List<SignatureContactsImportResult>',
            'signatureEnvelopeFieldsResponseList': 'List<SignatureEnvelopeFieldsResponse>',
            'signatureTemplateDocumentInfoList': 'List<SignatureTemplateDocumentInfo>',
            'signatureFieldSettingsList': 'List<SignatureFieldSettings>',
            'signatureTemplateFieldInfoList': 'List<SignatureTemplateFieldInfo>',
            'signatureRolesResultList': 'List<SignatureRolesResult>',
            'signatureTemplateResultList': 'List<SignatureTemplateResult>',
            'signatureEnvelopeRecipientsResponseList': 'List<SignatureEnvelopeRecipientsResponse>',
            'signatureRolesResponseList': 'List<SignatureRolesResponse>',
            'signatureContactsImportResponseList': 'List<SignatureContactsImportResponse>',
            'signatureEnvelopeFieldsResultList': 'List<SignatureEnvelopeFieldsResult>',
            'signatureEnvelopeFieldResponseList': 'List<SignatureEnvelopeFieldResponse>',
            'signatureTemplateResponseList': 'List<SignatureTemplateResponse>',
            'signatureEnvelopeDocumentResponseList': 'List<SignatureEnvelopeDocumentResponse>',
            'signatureSignaturesResponseList': 'List<SignatureSignaturesResponse>',
            'signatureTemplatesResponseList': 'List<SignatureTemplatesResponse>',
            'signatureSignatureSettingsList': 'List<SignatureSignatureSettings>',
            'signatureEnvelopeResultList': 'List<SignatureEnvelopeResult>',
            'signatureTemplateDocumentResponseList': 'List<SignatureTemplateDocumentResponse>',
            'signatureTemplateRecipientsResultList': 'List<SignatureTemplateRecipientsResult>',
            'signatureContactResultList': 'List<SignatureContactResult>',
            'signatureEnvelopeRecipientResponseList': 'List<SignatureEnvelopeRecipientResponse>',
            'signatureTemplateRecipientsResponseList': 'List<SignatureTemplateRecipientsResponse>',
            'signatureEnvelopeFieldResultList': 'List<SignatureEnvelopeFieldResult>',
            'signatureTemplateDocumentsResultList': 'List<SignatureTemplateDocumentsResult>',
            'signatureEnvelopeResourcesResultList': 'List<SignatureEnvelopeResourcesResult>',
            'signatureEnvelopeDocumentsResultList': 'List<SignatureEnvelopeDocumentsResult>',
            'signatureTemplatesResultList': 'List<SignatureTemplatesResult>',
            'signatureEnvelopeRecipientsResultList': 'List<SignatureEnvelopeRecipientsResult>',
            'signatureFieldResponseList': 'List<SignatureFieldResponse>',
            'signatureFieldsResponseList': 'List<SignatureFieldsResponse>',
            'signatureStatusResponseList': 'List<SignatureStatusResponse>',
            'signatureEnvelopeFieldLocationInfoList': 'List<SignatureEnvelopeFieldLocationInfo>',
            'signatureContactsResultList': 'List<SignatureContactsResult>',
            'signatureEnvelopeDocumentInfoList': 'List<SignatureEnvelopeDocumentInfo>',
            'signatureTemplateRecipientInfoList': 'List<SignatureTemplateRecipientInfo>',
            'signatureTemplateDocumentsResponseList': 'List<SignatureTemplateDocumentsResponse>',
            'signatureSignatureResponseList': 'List<SignatureSignatureResponse>',
            'signatureEnvelopeDocumentResultList': 'List<SignatureEnvelopeDocumentResult>',
            'signatureTemplateFieldResultList': 'List<SignatureTemplateFieldResult>',
            'signatureTemplateInfoList': 'List<SignatureTemplateInfo>',
            'signatureSignatureResultList': 'List<SignatureSignatureResult>',
            'signatureFieldsResultList': 'List<SignatureFieldsResult>',
            'signatureContactSettingsList': 'List<SignatureContactSettings>',
            'signatureEnvelopeRecipientInfoList': 'List<SignatureEnvelopeRecipientInfo>',
            'signatureEnvelopeSettingsList': 'List<SignatureEnvelopeSettings>',
            'signatureEnvelopeFieldSettingsList': 'List<SignatureEnvelopeFieldSettings>',
            'signatureContactInfoList': 'List<SignatureContactInfo>',
            'signatureEnvelopeFieldLocationSettingsList': 'List<SignatureEnvelopeFieldLocationSettings>',
            'signatureEnvelopeResponseList': 'List<SignatureEnvelopeResponse>',
            'signatureSignaturesResultList': 'List<SignatureSignaturesResult>',
            'signatureEnvelopeResourcesResponseList': 'List<SignatureEnvelopeResourcesResponse>'
        }



        # 
        self.documentDetailsResponseList = None # List<DocumentDetailsResponse>


        # 
        self.changesResponseList = None # List<ChangesResponse>


        # 
        self.changesResultList = None # List<ChangesResult>


        # 
        self.documentDetailsResultList = None # List<DocumentDetailsResult>


        # 
        self.compareResultList = None # List<CompareResult>


        # 
        self.pageList = None # List<Page>


        # 
        self.compareResponseList = None # List<CompareResponse>


        # 
        self.rectangleList = None # List<Rectangle>


        # 
        self.changeInfoList = None # List<ChangeInfo>


        # 
        self.resetPasswordResultList = None # List<ResetPasswordResult>


        # 
        self.createUserResultList = None # List<CreateUserResult>


        # 
        self.userPasswordInfoList = None # List<UserPasswordInfo>


        # 
        self.updateStorageProviderResponseList = None # List<UpdateStorageProviderResponse>


        # 
        self.createUserResponseList = None # List<CreateUserResponse>


        # 
        self.changePasswordResultList = None # List<ChangePasswordResult>


        # 
        self.updateUserResponseList = None # List<UpdateUserResponse>


        # 
        self.addStorageProviderResponseList = None # List<AddStorageProviderResponse>


        # 
        self.updateUserResultList = None # List<UpdateUserResult>


        # 
        self.userInfoResponseList = None # List<UserInfoResponse>


        # 
        self.getStorageProvidersResultList = None # List<GetStorageProvidersResult>


        # 
        self.resetPasswordResponseList = None # List<ResetPasswordResponse>


        # 
        self.updateStorageProviderResultList = None # List<UpdateStorageProviderResult>


        # 
        self.userInfoList = None # List<UserInfo>


        # 
        self.addStorageProviderResultList = None # List<AddStorageProviderResult>


        # 
        self.getStorageProvidersResponseList = None # List<GetStorageProvidersResponse>


        # 
        self.userInfoResultList = None # List<UserInfoResult>


        # 
        self.storageProviderInfoList = None # List<StorageProviderInfo>


        # 
        self.changePasswordResponseList = None # List<ChangePasswordResponse>


        # 
        self.setCollaboratorsResponseList = None # List<SetCollaboratorsResponse>


        # 
        self.listRepliesResultList = None # List<ListRepliesResult>


        # 
        self.listAnnotationsResponseList = None # List<ListAnnotationsResponse>


        # 
        self.rangeList = None # List<Range>


        # 
        self.annotationInfoList = None # List<AnnotationInfo>


        # 
        self.getCollaboratorsResponseList = None # List<GetCollaboratorsResponse>


        # 
        self.userIdentityList = None # List<UserIdentity>


        # 
        self.moveAnnotationResultList = None # List<MoveAnnotationResult>


        # 
        self.editReplyResponseList = None # List<EditReplyResponse>


        # 
        self.addReplyResultList = None # List<AddReplyResult>


        # 
        self.addReplyResponseList = None # List<AddReplyResponse>


        # 
        self.createAnnotationResponseList = None # List<CreateAnnotationResponse>


        # 
        self.deleteAnnotationResultList = None # List<DeleteAnnotationResult>


        # 
        self.deleteAnnotationResponseList = None # List<DeleteAnnotationResponse>


        # 
        self.createAnnotationResultList = None # List<CreateAnnotationResult>


        # 
        self.annotationReplyInfoList = None # List<AnnotationReplyInfo>


        # 
        self.listRepliesResponseList = None # List<ListRepliesResponse>


        # 
        self.moveAnnotationResponseList = None # List<MoveAnnotationResponse>


        # 
        self.editReplyResultList = None # List<EditReplyResult>


        # 
        self.listAnnotationsResultList = None # List<ListAnnotationsResult>


        # 
        self.setCollaboratorsResultList = None # List<SetCollaboratorsResult>


        # 
        self.pointList = None # List<Point>


        # 
        self.getCollaboratorsResultList = None # List<GetCollaboratorsResult>


        # 
        self.resultList = None # List<Result>


        # 
        self.getJobsDocumentsResultList = None # List<GetJobsDocumentsResult>


        # 
        self.getJobDocumentsResultList = None # List<GetJobDocumentsResult>


        # 
        self.createJobResponseList = None # List<CreateJobResponse>


        # 
        self.getJobDocumentsResponseList = None # List<GetJobDocumentsResponse>


        # 
        self.createJobResultList = None # List<CreateJobResult>


        # 
        self.getJobsResponseList = None # List<GetJobsResponse>


        # 
        self.jobInputDocumentList = None # List<JobInputDocument>


        # 
        self.convertResponseList = None # List<ConvertResponse>


        # 
        self.getJobResponseList = None # List<GetJobResponse>


        # 
        self.addJobDocumentResponseList = None # List<AddJobDocumentResponse>


        # 
        self.getJobsDocumentsResponseList = None # List<GetJobsDocumentsResponse>


        # 
        self.getJobsResultList = None # List<GetJobsResult>


        # 
        self.updateJobResponseList = None # List<UpdateJobResponse>


        # 
        self.getJobResultList = None # List<GetJobResult>


        # 
        self.jobOutputDocumentList = None # List<JobOutputDocument>


        # 
        self.convertRequestResultList = None # List<ConvertRequestResult>


        # 
        self.jobDocumentsEntryList = None # List<JobDocumentsEntry>


        # 
        self.jobInfoList = None # List<JobInfo>


        # 
        self.addJobDocumentResultList = None # List<AddJobDocumentResult>


        # 
        self.viewDocumentResultList = None # List<ViewDocumentResult>


        # 
        self.viewDocumentResponseList = None # List<ViewDocumentResponse>


        # 
        self.dimensionList = None # List<Dimension>


        # 
        self.createPackageResultList = None # List<CreatePackageResult>


        # 
        self.uploadResponseList = None # List<UploadResponse>


        # 
        self.compressResponseList = None # List<CompressResponse>


        # 
        self.deleteResultList = None # List<DeleteResult>


        # 
        self.createFolderResultList = None # List<CreateFolderResult>


        # 
        self.folderMoveResultList = None # List<FolderMoveResult>


        # 
        self.fileMoveResultList = None # List<FileMoveResult>


        # 
        self.listEntitiesResultList = None # List<ListEntitiesResult>


        # 
        self.fileSystemDocumentList = None # List<FileSystemDocument>


        # 
        self.createFolderResponseList = None # List<CreateFolderResponse>


        # 
        self.documentInfoList = None # List<DocumentInfo>


        # 
        self.compressRequestResultList = None # List<CompressRequestResult>


        # 
        self.uploadRequestResultList = None # List<UploadRequestResult>


        # 
        self.storageInfoResultList = None # List<StorageInfoResult>


        # 
        self.createPackageResponseList = None # List<CreatePackageResponse>


        # 
        self.folderMoveResponseList = None # List<FolderMoveResponse>


        # 
        self.storageInfoResponseList = None # List<StorageInfoResponse>


        # 
        self.fileSystemFolderList = None # List<FileSystemFolder>


        # 
        self.deleteResponseList = None # List<DeleteResponse>


        # 
        self.listEntitiesResponseList = None # List<ListEntitiesResponse>


        # 
        self.fileMoveResponseList = None # List<FileMoveResponse>


        # 
        self.getDocumentInfoResultList = None # List<GetDocumentInfoResult>


        # 
        self.templateFieldList = None # List<TemplateField>


        # 
        self.documentViewsResultList = None # List<DocumentViewsResult>


        # 
        self.sharedDocumentsResponseList = None # List<SharedDocumentsResponse>


        # 
        self.templateFieldsResponseList = None # List<TemplateFieldsResponse>


        # 
        self.documentAccessInfoResultList = None # List<DocumentAccessInfoResult>


        # 
        self.sharedUsersResultList = None # List<SharedUsersResult>


        # 
        self.sharedDocumentsResultList = None # List<SharedDocumentsResult>


        # 
        self.documentViewsResponseList = None # List<DocumentViewsResponse>


        # 
        self.getDocumentForeignTypesResponseList = None # List<GetDocumentForeignTypesResponse>


        # 
        self.documentViewInfoList = None # List<DocumentViewInfo>


        # 
        self.sharedUsersResponseList = None # List<SharedUsersResponse>


        # 
        self.getDocumentInfoResponseList = None # List<GetDocumentInfoResponse>


        # 
        self.documentUserStatusResultList = None # List<DocumentUserStatusResult>


        # 
        self.documentUserStatusResponseList = None # List<DocumentUserStatusResponse>


        # 
        self.templateFieldsResultList = None # List<TemplateFieldsResult>


        # 
        self.getDocumentForeignTypesResultList = None # List<GetDocumentForeignTypesResult>


        # 
        self.documentAccessInfoResponseList = None # List<DocumentAccessInfoResponse>


        # 
        self.sharedDocumentInfoList = None # List<SharedDocumentInfo>


        # 
        self.questionnaireExecutionInfoList = None # List<QuestionnaireExecutionInfo>


        # 
        self.getQuestionnairesResponseList = None # List<GetQuestionnairesResponse>


        # 
        self.getDocumentQuestionnairesResultList = None # List<GetDocumentQuestionnairesResult>


        # 
        self.addDocumentDataSourceResponseList = None # List<AddDocumentDataSourceResponse>


        # 
        self.getDatasourceResultList = None # List<GetDatasourceResult>


        # 
        self.getDatasourcesResponseList = None # List<GetDatasourcesResponse>


        # 
        self.addDocumentQuestionnaireResponseList = None # List<AddDocumentQuestionnaireResponse>


        # 
        self.updateQuestionnaireResultList = None # List<UpdateQuestionnaireResult>


        # 
        self.addQuestionnaireExecutionResponseList = None # List<AddQuestionnaireExecutionResponse>


        # 
        self.deleteDatasourceResponseList = None # List<DeleteDatasourceResponse>


        # 
        self.createQuestionnaireResultList = None # List<CreateQuestionnaireResult>


        # 
        self.createQuestionnaireResponseList = None # List<CreateQuestionnaireResponse>


        # 
        self.questionnaireInfoList = None # List<QuestionnaireInfo>


        # 
        self.addDatasourceResultList = None # List<AddDatasourceResult>


        # 
        self.questionnairePageInfoList = None # List<QuestionnairePageInfo>


        # 
        self.updateQuestionnaireExecutionResponseList = None # List<UpdateQuestionnaireExecutionResponse>


        # 
        self.getQuestionnaireExecutionsResultList = None # List<GetQuestionnaireExecutionsResult>


        # 
        self.deleteQuestionnaireResultList = None # List<DeleteQuestionnaireResult>


        # 
        self.getDocumentQuestionnairesResponseList = None # List<GetDocumentQuestionnairesResponse>


        # 
        self.getDatasourceResponseList = None # List<GetDatasourceResponse>


        # 
        self.addQuestionnaireExecutionResultList = None # List<AddQuestionnaireExecutionResult>


        # 
        self.deleteDocumentQuestionnaireResponseList = None # List<DeleteDocumentQuestionnaireResponse>


        # 
        self.mergeTemplateResponseList = None # List<MergeTemplateResponse>


        # 
        self.deleteDocumentQuestionnaireResultList = None # List<DeleteDocumentQuestionnaireResult>


        # 
        self.getQuestionnairesResultList = None # List<GetQuestionnairesResult>


        # 
        self.getQuestionnaireExecutionsResponseList = None # List<GetQuestionnaireExecutionsResponse>


        # 
        self.deleteQuestionnaireResponseList = None # List<DeleteQuestionnaireResponse>


        # 
        self.questionInfoList = None # List<QuestionInfo>


        # 
        self.datasourceList = None # List<Datasource>


        # 
        self.getQuestionnaireResultList = None # List<GetQuestionnaireResult>


        # 
        self.mergeTemplateResultList = None # List<MergeTemplateResult>


        # 
        self.answerInfoList = None # List<AnswerInfo>


        # 
        self.getDatasourcesResultList = None # List<GetDatasourcesResult>


        # 
        self.updateQuestionnaireExecutionResultList = None # List<UpdateQuestionnaireExecutionResult>


        # 
        self.addDocumentDataSourceResultList = None # List<AddDocumentDataSourceResult>


        # 
        self.deleteDatasourceResultList = None # List<DeleteDatasourceResult>


        # 
        self.addDocumentQuestionnaireResultList = None # List<AddDocumentQuestionnaireResult>


        # 
        self.updateQuestionnaireResponseList = None # List<UpdateQuestionnaireResponse>


        # 
        self.addDatasourceResponseList = None # List<AddDatasourceResponse>


        # 
        self.getQuestionnaireResponseList = None # List<GetQuestionnaireResponse>


        # 
        self.datasourceFieldList = None # List<DatasourceField>


        # 
        self.renameResponseList = None # List<RenameResponse>


        # 
        self.renameResultList = None # List<RenameResult>


        # 
        self.signatureEnvelopeDocumentsResponseList = None # List<SignatureEnvelopeDocumentsResponse>


        # 
        self.signatureFieldInfoList = None # List<SignatureFieldInfo>


        # 
        self.signatureContactResponseList = None # List<SignatureContactResponse>


        # 
        self.signatureEnvelopesResultList = None # List<SignatureEnvelopesResult>


        # 
        self.signatureTemplateFieldLocationInfoList = None # List<SignatureTemplateFieldLocationInfo>


        # 
        self.signatureTemplateDocumentResultList = None # List<SignatureTemplateDocumentResult>


        # 
        self.signatureContactsResponseList = None # List<SignatureContactsResponse>


        # 
        self.signatureFieldResultList = None # List<SignatureFieldResult>


        # 
        self.signatureSignatureInfoList = None # List<SignatureSignatureInfo>


        # 
        self.signatureTemplateFieldsResponseList = None # List<SignatureTemplateFieldsResponse>


        # 
        self.signatureEnvelopeInfoList = None # List<SignatureEnvelopeInfo>


        # 
        self.signatureTemplateFieldSettingsList = None # List<SignatureTemplateFieldSettings>


        # 
        self.signatureTemplateFieldLocationSettingsList = None # List<SignatureTemplateFieldLocationSettings>


        # 
        self.signatureEnvelopeRecipientResultList = None # List<SignatureEnvelopeRecipientResult>


        # 
        self.signatureTemplateFieldResponseList = None # List<SignatureTemplateFieldResponse>


        # 
        self.signatureEnvelopesResponseList = None # List<SignatureEnvelopesResponse>


        # 
        self.signatureEnvelopeFieldInfoList = None # List<SignatureEnvelopeFieldInfo>


        # 
        self.signatureRoleInfoList = None # List<SignatureRoleInfo>


        # 
        self.signatureTemplateSettingsList = None # List<SignatureTemplateSettings>


        # 
        self.signatureTemplateFieldsResultList = None # List<SignatureTemplateFieldsResult>


        # 
        self.signatureContactsImportResultList = None # List<SignatureContactsImportResult>


        # 
        self.signatureEnvelopeFieldsResponseList = None # List<SignatureEnvelopeFieldsResponse>


        # 
        self.signatureTemplateDocumentInfoList = None # List<SignatureTemplateDocumentInfo>


        # 
        self.signatureFieldSettingsList = None # List<SignatureFieldSettings>


        # 
        self.signatureTemplateFieldInfoList = None # List<SignatureTemplateFieldInfo>


        # 
        self.signatureRolesResultList = None # List<SignatureRolesResult>


        # 
        self.signatureTemplateResultList = None # List<SignatureTemplateResult>


        # 
        self.signatureEnvelopeRecipientsResponseList = None # List<SignatureEnvelopeRecipientsResponse>


        # 
        self.signatureRolesResponseList = None # List<SignatureRolesResponse>


        # 
        self.signatureContactsImportResponseList = None # List<SignatureContactsImportResponse>


        # 
        self.signatureEnvelopeFieldsResultList = None # List<SignatureEnvelopeFieldsResult>


        # 
        self.signatureEnvelopeFieldResponseList = None # List<SignatureEnvelopeFieldResponse>


        # 
        self.signatureTemplateResponseList = None # List<SignatureTemplateResponse>


        # 
        self.signatureEnvelopeDocumentResponseList = None # List<SignatureEnvelopeDocumentResponse>


        # 
        self.signatureSignaturesResponseList = None # List<SignatureSignaturesResponse>


        # 
        self.signatureTemplatesResponseList = None # List<SignatureTemplatesResponse>


        # 
        self.signatureSignatureSettingsList = None # List<SignatureSignatureSettings>


        # 
        self.signatureEnvelopeResultList = None # List<SignatureEnvelopeResult>


        # 
        self.signatureTemplateDocumentResponseList = None # List<SignatureTemplateDocumentResponse>


        # 
        self.signatureTemplateRecipientsResultList = None # List<SignatureTemplateRecipientsResult>


        # 
        self.signatureContactResultList = None # List<SignatureContactResult>


        # 
        self.signatureEnvelopeRecipientResponseList = None # List<SignatureEnvelopeRecipientResponse>


        # 
        self.signatureTemplateRecipientsResponseList = None # List<SignatureTemplateRecipientsResponse>


        # 
        self.signatureEnvelopeFieldResultList = None # List<SignatureEnvelopeFieldResult>


        # 
        self.signatureTemplateDocumentsResultList = None # List<SignatureTemplateDocumentsResult>


        # 
        self.signatureEnvelopeResourcesResultList = None # List<SignatureEnvelopeResourcesResult>


        # 
        self.signatureEnvelopeDocumentsResultList = None # List<SignatureEnvelopeDocumentsResult>


        # 
        self.signatureTemplatesResultList = None # List<SignatureTemplatesResult>


        # 
        self.signatureEnvelopeRecipientsResultList = None # List<SignatureEnvelopeRecipientsResult>


        # 
        self.signatureFieldResponseList = None # List<SignatureFieldResponse>


        # 
        self.signatureFieldsResponseList = None # List<SignatureFieldsResponse>


        # 
        self.signatureStatusResponseList = None # List<SignatureStatusResponse>


        # 
        self.signatureEnvelopeFieldLocationInfoList = None # List<SignatureEnvelopeFieldLocationInfo>


        # 
        self.signatureContactsResultList = None # List<SignatureContactsResult>


        # 
        self.signatureEnvelopeDocumentInfoList = None # List<SignatureEnvelopeDocumentInfo>


        # 
        self.signatureTemplateRecipientInfoList = None # List<SignatureTemplateRecipientInfo>


        # 
        self.signatureTemplateDocumentsResponseList = None # List<SignatureTemplateDocumentsResponse>


        # 
        self.signatureSignatureResponseList = None # List<SignatureSignatureResponse>


        # 
        self.signatureEnvelopeDocumentResultList = None # List<SignatureEnvelopeDocumentResult>


        # 
        self.signatureTemplateFieldResultList = None # List<SignatureTemplateFieldResult>


        # 
        self.signatureTemplateInfoList = None # List<SignatureTemplateInfo>


        # 
        self.signatureSignatureResultList = None # List<SignatureSignatureResult>


        # 
        self.signatureFieldsResultList = None # List<SignatureFieldsResult>


        # 
        self.signatureContactSettingsList = None # List<SignatureContactSettings>


        # 
        self.signatureEnvelopeRecipientInfoList = None # List<SignatureEnvelopeRecipientInfo>


        # 
        self.signatureEnvelopeSettingsList = None # List<SignatureEnvelopeSettings>


        # 
        self.signatureEnvelopeFieldSettingsList = None # List<SignatureEnvelopeFieldSettings>


        # 
        self.signatureContactInfoList = None # List<SignatureContactInfo>


        # 
        self.signatureEnvelopeFieldLocationSettingsList = None # List<SignatureEnvelopeFieldLocationSettings>


        # 
        self.signatureEnvelopeResponseList = None # List<SignatureEnvelopeResponse>


        # 
        self.signatureSignaturesResultList = None # List<SignatureSignaturesResult>


        # 
        self.signatureEnvelopeResourcesResponseList = None # List<SignatureEnvelopeResourcesResponse>

