language: python

python:
  - "2.6"
  - "2.7"

install:
  - pip install --use-mirrors unittest2;
  

script: nosetests tests/unit/
  - git clone --branch=master --depth=100 --quiet git://github.com/groupdocs/groupdocs-sdk-samples-uitests.git tests/ui
  - cd tests/ui
  - mvn -q -s settings.xml clean test
      
