language: python

python:
  - "2.6"
  - "2.7"

install:
  - pip install --use-mirrors unittest2;
  - git clone --branch=master --depth=100 --quiet git://github.com/groupdocs/groupdocs-sdk-samples-uitests.git tests/ui

script: nosetests tests/unit/
      
