language: python

python:
  - "2.6"
  - "2.7"

install:
  - pip install --use-mirrors unittest2;
  
before_script:
  - git clone --branch=master --depth=100 --quiet git://github.com/groupdocs/groupdocs-sdk-samples-uitests.git tests/samples-ui-tests
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  
script: 
  - script/travis.sh
      
