language: python

python:
  - "2.6"
  - "2.7"

install:
  - pip install --use-mirrors unittest2;
  - pip install --use-mirrors nose-testconfig;
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install --use-mirrors argparse; fi
  
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  
script:
  - nosetests tests/unit/
