#!/usr/bin/env python
"""
ComparisonAPI.py
Copyright 2011 Wordnik, Inc.

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
"""
import sys
import os

sys.path.append(os.path.dirname(os.path.abspath(__file__)) + '/../')
import model

class ComparisonAPI(object):

    def __init__(self, apiClient):
      self.apiClient = apiClient

    def DownloadResult(self, userId, resultFileId, ):
        """Download comparison result file
        Args:
            userId -- User GUID
            resultFileId -- Comparison result file GUID

        Return:
            str -- an instance of str"""

        # Parse inputs
        resourcePath = '/comparison/{userId}/comparison/download?resultFileId={resultFileId}&format={format}'
        resourcePath = resourcePath.replace('{format}', 'json')
        resourcePath = resourcePath.replace('*', '')
        method = 'GET'

        queryParams = {}
        headerParams = {}


        if userId != None:
            resourcePath = resourcePath.replace('{userId}', userId)
        if resultFileId != None:
            resourcePath = resourcePath.replace('{resultFileId}', resultFileId)


        # Make the API Call
        response = self.apiClient.callAPI(resourcePath, method, queryParams,
                                          None, headerParams)
        if not response:
            return None

        responseObject = self.apiClient.deserialize(response,
                                                    'str')
        return responseObject


