#!/usr/bin/env python
"""
ComparisonAPI.py
Copyright 2011 Wordnik, Inc.

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
"""
import sys
import os

sys.path.append(os.path.dirname(os.path.abspath(__file__)) + '/../')
import model

class ComparisonAPI(object):

    def __init__(self, apiClient):
      self.apiClient = apiClient

    def Compare(self, userId, sourceFileId, targetFileId, ):
        """Compare
        Args:
            userId -- User GUID
            sourceFileId -- Source File GUID
            targetFileId -- Target File GUID

        Return:
            CompareResponse -- an instance of CompareResponse"""

        # Parse inputs
        resourcePath = '/comparison/{userId}/comparison/compare?source={sourceFileId}&target={targetFileId}'
        resourcePath = resourcePath.replace('{format}', 'json')
        method = 'GET'

        queryParams = {}
        headerParams = {}


        if userId != None:
            resourcePath = resourcePath.replace('{userId}', userId)
        if sourceFileId != None:
            resourcePath = resourcePath.replace('{sourceFileId}', sourceFileId)
        if targetFileId != None:
            resourcePath = resourcePath.replace('{targetFileId}', targetFileId)


        # Make the API Call
        response = self.apiClient.callAPI(resourcePath, method, queryParams,
                                          None, headerParams)
        if not response:
            return None

        responseObject = self.apiClient.deserialize(response,
                                                    'CompareResponse')
        return responseObject


    def GetChanges(self, userId, resultFileId, ):
        """Get changes
        Args:
            userId -- User GUID
            resultFileId -- Comparison result file GUID

        Return:
            ChangesResponse -- an instance of ChangesResponse"""

        # Parse inputs
        resourcePath = '/comparison/{userId}/comparison/changes?resultFileId={resultFileId}'
        resourcePath = resourcePath.replace('{format}', 'json')
        method = 'GET'

        queryParams = {}
        headerParams = {}


        if userId != None:
            resourcePath = resourcePath.replace('{userId}', userId)
        if resultFileId != None:
            resourcePath = resourcePath.replace('{resultFileId}', resultFileId)


        # Make the API Call
        response = self.apiClient.callAPI(resourcePath, method, queryParams,
                                          None, headerParams)
        if not response:
            return None

        responseObject = self.apiClient.deserialize(response,
                                                    'ChangesResponse')
        return responseObject


    def GetDocumentDetails(self, userId, guid, ):
        """Get document details
        Args:
            userId -- User GUID
            guid -- Document GUID

        Return:
            DocumentDetailsResponse -- an instance of DocumentDetailsResponse"""

        # Parse inputs
        resourcePath = '/comparison/{userId}/comparison/document?guid={guid}'
        resourcePath = resourcePath.replace('{format}', 'json')
        method = 'GET'

        queryParams = {}
        headerParams = {}


        if userId != None:
            resourcePath = resourcePath.replace('{userId}', userId)
        if guid != None:
            resourcePath = resourcePath.replace('{guid}', guid)


        # Make the API Call
        response = self.apiClient.callAPI(resourcePath, method, queryParams,
                                          None, headerParams)
        if not response:
            return None

        responseObject = self.apiClient.deserialize(response,
                                                    'DocumentDetailsResponse')
        return responseObject


